


# # 1
# numero =  int(input('numero inteiro: '))
# quadrado =  numero ** 2
# print(quadrado)


# # 2


# nome = 'Beatriz'
# sobrenome = 'Alves'
# print(nome +  ' ' + sobrenome)
# print(nome, sobrenome)


# # 3


# n1  = int(input('numero inteiro:'))
# n2  = int(input('numero inteiro:'))
# print(str(n1), str(n2))


# # 4


# v = 'Python'
# print(v,10)


# # 5


# frase = 'Bom dia'
# nome  =  input('Nome: ')


# print(frase, nome)

# # +
# print('isso é um texto ' + ' ' + '10')
# # print(10 + 10)



# # ,
# print('isso é um texto ',  '10')



# # % 


# print('isso é um texto  %d'%(10))



# # .format()


# print('isso é um texto  {}'.format(10))



# # f-string


# print(f'isso é um texto  {10} ')


# 1 Imprima uma mensagem de boas-vindas na tela.
# print("hello python")


# 2 Declare uma variável booleana verdadeiro
# com o valor True e imprima seu tipo
# n = 10 > 1
# tipo = type(n)
# print(type, n)
# # 3 Imprima o resultado da multiplicação de dois números decimais de sua escolha
# print(0.25 * 0.25)
# # 4 Imprima o resultado da divisão (/)de dois números inteiros # de sua escolha.
# print(100 / 2)


# # 5 Imprima o resultado da subtração de dois números inteiros de sua escolha
# print(100 - 100)

# # 6 Imprima o resultado da divisão (//)inteira de dois números inteiros 
# # de sua escolha.
# print(100 // 99)
# # 7 Imprima o resultado da multiplicação de 4 números 
# # decimais de sua escolha
# print(0.25 * 0.25 * 0.25 *0.25)

# # 8 Declare uma variável numero e atribua um número inteiro. Em seguida, 
# # imprima o dobro desse número

# numero = 10
# print(numero * 2)
# 9 Crie um sistema de cadastro com as estruturas que vc já 
# conhece(Use apenas input, print e variavel)
# # nome, email, idade, cidade, gradução, estado civil 

# nome = str(input("Digite seu nome"))
# email = str(input("Digite seu email"))
# cidade = str(input("Digite sua cidade"))
# graduacao = str(input("Digite sua graduacao"))
# estado_civil = str(input("Digite seu estado civil"))

# print(f'seu nome é: ', nome, f'Seu email é: ', email, f'Sua cidade é: ', cidade, f'Sua graduacao é: ', graduacao, f'Seu estado civil é: ', estado_civil)