# n1  =  float(input('Nº'))
# op =  input('Digite a operação: ')
# n2  =  float(input('Nº'))
# resultado =  (op == '+' and (n1 +  n2)) or (op == '-' and n1 - n2) or (op == '*' and n1 * n2) or (op == '/' and n1 /n2)


# print(resultado)



# # __________________________________________________________________
# idade  =  int(input('Idade: '))
# carta_motorista = input('Possui carta: ')


# resultado = (idade >= 18 and carta_motorista == 'sim' and ('Pode dirigir...')) or ('Não pode ...')


# print(resultado)

### 1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.

# digite = int(input("Dig11   ite Um número"))
# print(digite ** 2)

### 2 - Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.
# n1 = input("Digite nome")
# n2 = input("Digite Sobrenome")
# nome= (n1 + n2)
# print(nome)

### 3 - Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.
# n1 = int(input("digite numero"))
# n2 = int(input("digite numero"))

# numeros = n1 + n2
# print(numeros) 

### 4 - Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.

# palavra = "Python"
# numero = 100

# new = palavra , numero 

# print(new)

### 5 - Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

# var = "Esse mundo é muito"

# var2 = input("Digite palavra")

# print(var + var2)

